### ISSUE TITLE
why this happened？please~~~

### ISSUE THREAD

**Issue by C00LMIN** [LunaticTian/TieBa-API-Sentiment#1]
`C:\Python\python.exe C:/Users/KONMIN/Desktop/TieBa-API-Sentiment-master/myitchat.py
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as 黑白配

Traceback (most recent call last):
  File "C:/Users/KONMIN/Desktop/TieBa-API-Sentiment-master/myitchat.py", line 137, in <module>
    itchat.auto_login(hotReload=True)

  File "C:\Python\lib\site-packages\itchat\components\register.py", line 33, in auto_login
    self.dump_login_status(statusStorageDir)

  File "C:\Python\lib\site-packages\itchat\components\hotreload.py", line 31, in dump_login_status
    with open(fileDir, 'wb') as f:

PermissionError: [Errno 13] Permission denied: 'itchat.pkl'
`
i dont know why，  yingyingying....

**Comment by LunaticTian** [comment]
“Permission denied”，please start as root..
