### ISSUE TITLE
微信登陆失败Your wechat account may be LIMITED to log in WEB wechat

### ISSUE THREAD

**Issue by ChengShiming** [LunaticTian/TieBa-API-Sentiment#2]
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
Start auto replying.
初始化
Traceback (most recent call last):
  File "D:\_dev\_other\TieBa-API-Sentiment\tieba.py", line 293, in ini
    F = open('list.tieba','r',encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'list.tieba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myitchat.py", line 144, in <module>
    tieba.ini()
  File "D:\_dev\_other\TieBa-API-Sentiment\tieba.py", line 297, in ini
    GetText(GetId())
  File "D:\_dev\_other\TieBa-API-Sentiment\tieba.py", line 75, in GetId
    test = TiebaApiUtil.GetPage(key=name,Start=Start,End=End)
  File "D:\_dev\_other\TieBa-API-Sentiment\TiebaApiUtil.py", line 74, in GetPage
    Soup = BeautifulSoup(GetPageID.text,'lxml')
  File "C:\Python\Python38-32\lib\site-packages\bs4\__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by LunaticTian** [comment]
这是由于你登录的账号为新账号，微信web不在接受新账号的登录。
